### ISSUE TITLE
CI runs twice on pull request

### ISSUE THREAD

**Issue by vhschlenker** [Mari-Wie/ArchCNL#166]
Currently, the CI runs twice on a pull request.

That is caused by this line:
https://github.com/Mari-Wie/ArchCNL/blob/8536805b47c36e41449e8d4b81b649bed716e6c4/.github/workflows/build.yml#L3
This line translates to "run the CI on any push (inclusive-)or pull request".
A better strategy should be decided, when the CI should run.
Either on every push (and omitting the "pull_request"), or on every push to master and for every pull request, like this:
```yml
on:
  push:
    branches:
      - master
  pull_request:
```
Or something else.
